# Generated by Django 5.2.5 on 2025-09-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('B.Tech CSE', 'B.Tech Computer Science Engineering'), ('B.Tech IT', 'B.Tech Information Technology'), ('B.Tech ECE', 'B.Tech Electronics & Communication'), ('B.Tech ME', 'B.Tech Mechanical Engineering'), ('B.Tech CE', 'B.Tech Civil Engineering'), ('B.Tech EE', 'B.Tech Electrical Engineering'), ('BCA', 'Bachelor of Computer Applications'), ('MCA', 'Master of Computer Applications'), ('MBA', 'Master of Business Administration'), ('B.Sc CS', 'B.Sc Computer Science'), ('M.Tech', 'Master of Technology')], default='B.Tech CSE', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year'), ('Final', 'Final Year')], default='1st', max_length=10),
        ),
    ]
